past/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("posts/", include("posts.urls")), path("admin/", admin.site.urls)]

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.HistoryView.as_view(), name="history"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("analytics/", views.analytics, name="analytics"),
    path("delete/<int:pk>/", views.DeleteView.as_view(), name="delete"),
    path(
        "analytics/groupingpie/json",
        views.GroupingPieChartJSONView.as_view(),
        name="analyticsgroupingpiejson",
    ),
    path(
        "analytics/pastdaypie/json",
        views.PastDayPieChartJSONView.as_view(),
        name="analyticspastdaypiejson",
    ),
    path(
        "analytics/averagehours/json",
        views.AverageHoursJSONView.as_view(),
        name="analyticsaveragehoursjson",
    ),
]

posts/models.py
from django.db import models


class Event(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-pub_date"]

    def was_important(self):
        return self.title != "*"

posts/views.py
import random
import re
import sqlite3
from collections import defaultdict
from datetime import datetime
from functools import reduce

import matplotlib.pyplot as plt
import numpy as np
from django import forms
from django.forms import Textarea
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic

import pandas as pd
from chartjs.views.lines import BaseLineChartView
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from pandas.io import sql

from .models import Event


class IndexView(generic.ListView):
    template_name = "posts/index.html"
    context_object_name = "latest_posts"

    def get_queryset(self):
        return Event.objects.all()[:10]


class HistoryView(generic.DetailView):
    model = Event
    template_name = "posts/history.html"
    context_object_name = "post"


class CreateView(generic.edit.CreateView):
    model = Event
    fields = ["title", "text"]
    exclude = ["pub_date"]
    widgets = {"text": Textarea(attrs={"cols": 100, "rows": 15})}
    template_name = "posts/create.html"

    def get_success_url(self):
        return reverse("posts:index")


class Graph:
    def __init__(self, n):
        self.number_edges = n
        self.visited = [False] * n
        self.adj = defaultdict(list)
        self.connections = []

    def add_edge(self, n1, n2):
        self.adj[n1].append(n2)
        self.adj[n2].append(n1)

    def dfs(self):
        for i in range(self.number_edges):
            if not self.visited[i]:
                self.connections.append([])
                self.traverse_adj(i)

    def traverse_adj(self, i):
        self.connections[len(self.connections) - 1].append(i)
        self.visited[i] = True
        for j in self.adj[i]:
            if not self.visited[j]:
                self.traverse_adj(j)


class EventAnalysis:
    def __init__(self):
        conn = sqlite3.connect("db.sqlite3")
        self.data = sql.read_sql("SELECT * FROM posts_event;", con=conn)
        conn.close()
        self.clean_data()
        self.feature_engineering()

    def string_clean(self, s):
        s = re.sub("[^a-zA-Z ]+", "", s).lower()
        s = re.sub(" +", " ", s).strip().split(" ")
        stop_words = set(stopwords.words("english"))
        s = [w for w in s if not w in stop_words]
        ps = PorterStemmer()
        s = list(set([ps.stem(w) for w in s]))
        return s

    def clean_data(self):
        self.data["cleansed_title"] = self.data["title"].map(self.string_clean)
        self.data["cleansed_text"] = self.data["text"].map(self.string_clean)

    def calculate_hours(self, time1, time2):
        def difference(idx1, idx2):
            return int(time2[idx1:idx2]) - int(time1[idx1:idx2])

        year = difference(0, 4)
        month = difference(5, 7)
        day = difference(8, 10)
        hour = difference(11, 13)
        minute = difference(14, 16)
        return year * 365 * 24 + month * 30 * 24 + day * 24 + hour + minute / 60

    def feature_engineering(self):
        time_spent, day_id = [1], []
        anchor_day, day_i = self.data["pub_date"][0][:10], 1
        for i in range(self.data.shape[0]):
            if i != 0:
                time_spent.append(
                    self.calculate_hours(
                        self.data["pub_date"][i - 1], self.data["pub_date"][i]
                    )
                )
            if self.data["pub_date"][i][:10] != anchor_day:
                day_i += 1
                anchor_day = self.data["pub_date"][i][:10]
            day_id.append(day_i)
        self.last_day_id = day_i
        self.data["time_spent"] = time_spent
        self.data["day_id"] = day_id
        self.data["is_important"] = self.data["title"].map(lambda x: x != "*")

        connected_components = Graph(len(self.data["id"]))
        added_edges = set()
        for i, title in enumerate(self.data["cleansed_title"]):
            for j, other in enumerate(self.data["cleansed_title"]):
                if (
                    i != j
                    and set(title) & set(other)
                    and frozenset({i, j}) not in added_edges
                ):
                    connected_components.add_edge(i, j)
                    added_edges.add(frozenset({i, j}))
        connected_components.dfs()
        group_number = 1
        id_group = dict()
        for group in connected_components.connections:
            for n in group:
                id_group[n] = group_number
            group_number += 1
        self.last_group_number = group_number
        self.data["group_id"] = [id_group[i] for i in range(self.data.shape[0])]
        self.data["pub_date_datetime"] = pd.to_datetime(
            self.data["pub_date"], format="%Y-%m-%d %H:%M:%S", errors="coerce"
        )
        time = pd.DataFrame(self.data[["pub_date_datetime", "time_spent"]])
        time = time.set_index(["pub_date_datetime"])
        time = time.resample("D").mean()
        self.time_df = time

    def past_day_pie(self):
        past_day = self.data[self.data.day_id == self.last_day_id]
        total = sum(past_day["time_spent"])
        percentages = past_day["time_spent"].map(lambda x: x / total)
        return list(percentages), list(past_day["title"])

    def grouping_pie(self):
        group_hours, group_words = [], []
        for i in range(1, self.last_group_number):
            group = self.data[self.data.group_id == i]
            group_hours.append(sum(group["time_spent"]))
            words = reduce(lambda a, b: set(a) | set(b), group["cleansed_title"], [])
            group_words.append(
                "\n".join(
                    [
                        w
                        for w in set(
                            random.sample(words, 4 if 4 <= len(words) else len(words))
                        )
                    ]
                )
            )
        return group_hours, group_words

    def time_plot(self):
        return (list(self.time_df["time_spent"]), self.time_df.index.tolist())


def analytics(request):
    if len(Event.objects.all()) > 0:
        print(e.data)
    return render(
        request, "posts/analytics.html", context={"events": Event.objects.all()}
    )


class DeleteView(generic.DeleteView):
    model = Event

    def get_success_url(self):
        return reverse("posts:index")


class ChartJSONView(BaseLineChartView):
    def __init__(self, method):
        self.stats, self.labels = method

    def get_labels(self):
        return self.labels

    def get_data(self):
        return [self.stats]

    def get_context_data(self):
        return {"labels": self.get_labels(), "datasets": self.get_datasets()}


e = EventAnalysis()


class GroupingPieChartJSONView(ChartJSONView):
    def __init__(self):
        super().__init__(e.grouping_pie())


class PastDayPieChartJSONView(ChartJSONView):
    def __init__(self):
        super().__init__(e.past_day_pie())


class AverageHoursJSONView(ChartJSONView):
    def __init__(self):
        super().__init__(e.time_plot())

posts/templates/posts/analytics.html
{% extends 'posts/base.html' %}
{% block content %}
  {% if events != None %}
    {% if events.count < 10 %}
      <p class="lead">Please come back when you have 10 events. No rush.</p>
    {% elif events %}
      <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
      <div class="row">
        <div class="col-lg-4">
          <canvas id="group_pie" width="500" height="500"></canvas>
        </div>
        <div class="col-lg-4">
          <canvas id="past_day_pie" width="500" height="500" class="offset-md-6"></canvas>
        </div>
      </div>
      <script type="text/javascript">
        function arrayRandomColors(len) {
          var arr = [];
          for (var i = 0; i < len; i++) {
            arr.push('#' + (Math.random().toString(16) + '0000000').slice(2, 8));
          }
          return arr;
        }
        function pieGraphGet(url, attribute, title) {
          $.get(url, function(data) {
            var ctx = $(attribute).get(0).getContext("2d");
            var labels = data['labels'];
            var data = data['datasets'][0]['data'];
            new Chart(ctx, {
              type: 'pie',
              data: {
                datasets: [{
                  data: data,
                  backgroundColor: arrayRandomColors(data.length),
                  hoverBackgroundColor: arrayRandomColors(data.length)
                }],
                labels: labels
              },
              options: {
                legend: {
                  labels: {
                    fontColor: "white"
                  }
                },
                title: {
                  fontColor: "white",
                  fontSize: 18,
                  display: true,
                  text: title
                },
                responsive: false
              }
            });
          });
        }
        pieGraphGet("{% url 'posts:analyticsgroupingpiejson' %}", "#group_pie", "Grouping events by connecting titles");
        pieGraphGet("{% url 'posts:analyticspastdaypiejson' %}", "#past_day_pie", "Past day events");
      </script>
      <canvas id="average_hours" width="1000" height="500"></canvas>
      <script type="text/javascript">
        $.get("{% url 'posts:analyticsaveragehoursjson' %}", function(data) {
          function jsonMaker(date, hour) {
            return {
              t: date,
              y: hour
            }
          }
          var formattedData = [];
          for (var i = 0; i < data.labels.length; i++) {
            formattedData.push(jsonMaker(data.labels[i], data['datasets'][0]['data'][i]));
          }
          var ctx = $('#average_hours').get(0).getContext("2d");
          new Chart(ctx, {
            type: 'line',
            data: {
              datasets: [{
                data: formattedData,
                backgroundColor: "#123456",
                label: "Avg event hours",
                fill: false,
                borderColor: "#654321",
                pointRadius: 0
              }]
            },
            options: {
              scales: {
                xAxes: [{
                  type: 'time',
                  distribution: 'series',
                  time: {
                    unit: 'day'
                  },
                  ticks: {
                    fontColor: "#ffffff"
                  },
                  gridLines: {
                    display: false
                  },
                  scaleLabel: {
                    display: true,
                  }
                }],
                yAxes: [{
                  scaleLabel: {
                  },
                  ticks: {
                    fontColor: "#ffffff"
                  },
                  gridLines: {
                    display: false,
                    font: "#ffffff"
                  }
                }]
              },
              title: {
                fontColor: "black",
                fontSize: 18,
                display: true,
                text: "Average event time per day"
              },
              responsive: true
            }
          });
        });
      </script>
    {% endif %}
  {% else %}
    <p class="lead">I am not detecting any posts.</p>
  {% endif %}
{% endblock %}

posts/templates/posts/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link btn-outline-success" href="{% url 'posts:index' %}">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link btn-outline-success" href="{% url 'posts:create' %}">Create an event</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link btn-outline-success" href="{% url 'posts:analytics' %}">Analytics</a>
            </li>
          </ul>
        </div>
        <a class="navbar-brand pull-right btn-outline-danger" href="#">Past patterns</a>
      </nav>
    </header>
    <main role="main" class="flex-shrink-0">
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

posts/templates/posts/create.html
{% extends 'posts/base.html' %}
{% block content %}
  <div class="contrast">
    <ol>
      <li>Title and write about what you just did.</li>
      <li>If you wasted time/can't remember, put a <b>*</b> in the title.</li>
      <li>Be consistent with your titles if you want better analytics 
        (don't put dinner one time and eating another; put dinner or eating both times).
      </li>
      <li>If you want to group a new event with an old one, put the
        old and new event together in the new title (old: {eating}, new: {eating, YouTube}).
      </li>
    </ol>
  </div>
  <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form>
{% endblock %}

posts/templates/posts/history.html
{% extends 'posts/base.html' %}
{% block content %}
  <p class="lead"> {{ post.title }} </p>
  {{ post.text|linebreaks }}
{% endblock %}

posts/templates/posts/index.html
{% extends 'posts/base.html' %}
{% block content %}
  <h1>Hello world!</h1>
  <p class="lead">
    Here are your recent posts:
  </p>
  {% if latest_posts %}
    <table class="table table-striped table-dark table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Date</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for post in latest_posts %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{% url 'posts:history' post.id %}">{{ post }}</a></td>
            <td>{{ post.pub_date }}</td>
            <td>
              <form name="delete" action="{% url 'posts:delete' post.id %}" method="post">
                {% csrf_token %}<input type="submit" value="X" class="rounded">
              </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="lead">You have not made any posts yet.</p>
  {% endif %}
{% endblock %}